Repository Nubblee/Nubble-FE, pull requests merged in 2024-09, with the labels that each got.

#20 setting/globalStyle 버튼 스타일 리셋, 마크다운 관련 style 추가
  src/constants/font.ts
  src/styles/GlobalStyles.tsx
Labels: 🛠️ Setting

#21 design/buttonComponent 버튼 컴포넌트 구현 (#2)
  src/components/Button.tsx
  src/constants/color.ts
  src/index.css
  src/main.tsx
  src/styles/GlobalStyles.tsx
Labels: 📝 Design

#23 [setting] 라우팅 초기설정
  package.json
  src/App.tsx
  src/layout/Layout.tsx
  src/pages/ErrorPage.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/routes/router.tsx
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 🛠️ Setting

#25 [Design] 로고 컴포넌트 구현
  index.html
  src/App.css
  src/App.tsx
  src/assets/logo.svg
  src/assets/react.svg
  src/components/Logo.tsx
Labels: 📝 Design

#28 [Design] 로그인 페이지 UI 구현
  src/layout/Layout.tsx
  src/pages/Login.tsx
Labels: 📝 Design

#29 [Design] 배너 컴포넌트 구현
  package.json
  src/components/Banner.tsx
  yarn.lock
Labels: 📝 Design

#31 [Design]플로팅메뉴(좋아요,공유) 디자인
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/help.yml
  .prettierrc
  README.md
  eslint.config.js
  package.json
  src/components/FloatingMenu.tsx
  src/pages/Home.tsx
  tsconfig.json
  tsconfig.node.json
Labels: 📝 Design

#30 [fix] 버튼 기본 props 추가
  src/components/Button.tsx
Labels: ☠ Fix

#34 [Design] 임시 글 목록 페이지 UI 구현
  src/components/Header.tsx
  src/pages/Saves.tsx
  src/routes/router.tsx
Labels: 📝 Design

#36 [Design] 글 작성 페이지 UI 작성 및 마크다운 적용
  package.json
  src/components/RenderMarkdown.tsx
  src/components/SelectBox.tsx
  src/layout/Layout.tsx
  src/pages/WritePage.tsx
  src/routes/router.tsx
  src/styles/GlobalStyles.tsx
  yarn.lock
Labels: 📝 Design

#37 [Design] bestContents UI 구현
  src/components/BestContents.tsx
  src/pages/Home.tsx
Labels: 📝 Design

#38 [Design] 게시물 미리보기 페이지 UI 구현
  src/pages/PreviewPage.tsx
  src/routes/router.tsx
Labels: 📝 Design

#48 [Design] homePage UI 구현
  src/components/BestContents.tsx
  src/pages/Home.tsx
Labels: 📝 Design

#49 [fix] 마크다운 이미지 형식 렌더링되도록 수정 (#7)
  src/components/RenderMarkdown.tsx
  src/pages/WritePage.tsx
  src/styles/GlobalStyles.tsx
Labels: ☠ Fix

#50 [Design] 글 수정하기 페이지 UI구현
  src/pages/WritePage.tsx
Labels: 📝 Design

#51 [Design] 모달 컴포넌트 UI 구현
  package.json
  src/components/Modal.tsx
  src/stores/useModalStore.ts
  src/styles/GlobalStyles.tsx
  yarn.lock
Labels: 📝 Design

#52 [Feature] 로그인 API 받아와서 로그인 기능 구현
  package.json
  src/pages/Login.tsx
  yarn.lock
Labels: ✨ Feature

#54 [Feature] 헤더에 로그인 정보 받아오기
  src/components/Header.tsx
  src/pages/Login.tsx
  src/stores/authStore.ts
Labels: ✨ Feature

#55 [ Design] 홈페이지 디자인 수정
  src/components/Banner.tsx
  src/components/BestContents.tsx
  src/pages/Home.tsx
  src/styles/GlobalStyles.tsx
Labels: 📝 Design

#58 [Feature] 로그인 상태 유지 구현
  src/hooks/useCheckSession.ts
  src/pages/ErrorPage.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/stores/authStore.ts
Labels: ✨ Feature

#63 [Feature] 유저 정보 업데이트
  src/components/Header.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/stores/authStore.ts
Labels: ✨ Feature

#67 [feat] 매인 배너에 오늘의 코테 문제 api 적용
  .gitignore
  src/components/Banner.tsx
Labels: ✨ Feature
