Repository Nubblee/Nubble-FE, pull requests merged in 2024-10, with the labels that each got.

#68 [feature] git 코테 풀이 api 가져와서 메인 목록, 상세페이지에 적용
  eslint.config.js
  package.json
  src/components/Banner.tsx
  src/hooks/useCoteData.ts
  src/pages/Home.tsx
  src/pages/PostDetail.tsx
  src/routes/router.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#71 [Fix] 코테 데이터 최신순으로 불러오기
  src/hooks/useCoteData.ts
  src/pages/Home.tsx
  src/pages/PostDetail.tsx
  src/utils/formatDate.ts
  yarn.lock
Labels: ☠ Fix

#72 [Feature] 메인페이지 Tab기능 구현
  src/components/Header.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/stores/authStore.ts
  src/stores/modalStore.ts
  yarn.lock
Labels: ✨ Feature

#73 [Feat] 파일 업로드 api 적용
  src/hooks/useCategory.ts
  src/hooks/useFileUpload.ts
  src/pages/WritePage.tsx
Labels: ✨ Feature

#76 [Feat] 글쓰기 페이지 -> 미리보기 페이지 이동
  src/components/SelectBox.tsx
  src/hooks/useGoBack.ts
  src/pages/PreviewPage.tsx
  src/pages/WritePage.tsx
  src/stores/writeStore.ts
Labels: ✨ Feature

#78 [fix] useWriteStore로 변경
  src/stores/writeStore.ts
Labels: ☠ Fix

#80 [feat] 카테고리 api적용
  src/components/SelectBox.tsx
  src/pages/WritePage.tsx
  src/stores/writeStore.ts
Labels: ✨ Feature

#82 [Fix] 글쓰기 카테고리 상태 값 수정
  src/hooks/useWrite.ts
  src/pages/WritePage.tsx
  src/stores/writeStore.ts
Labels: ☠ Fix

#85 [Feat] 글쓰기 임시저장 기능 구현
  src/hooks/useWrite.ts
  src/pages/WritePage.tsx
  src/stores/writeStore.ts
Labels: ✨ Feature

#87 [Design] 토스트 컴포넌트 구현
  package.json
  src/components/Toast.tsx
  yarn.lock
Labels: 📝 Design

#88 [Feature] 미리보기 페이지 기능 구현
  src/components/Toast.tsx
  src/hooks/useWrite.ts
  src/main.tsx
  src/pages/PostDetail.tsx
  src/pages/PreviewPage.tsx
  src/pages/WritePage.tsx
  src/routes/router.tsx
  src/stores/writeStore.ts
Labels: ✨ Feature

#89 [Chore] api url 환경변수로 이동
  src/components/Banner.tsx
  src/hooks/useCheckSession.ts
  src/hooks/useCoteData.ts
  src/hooks/useFileUpload.ts
  src/pages/AddQuestion.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/PreviewPage.tsx
  src/pages/WritePage.tsx
Labels: 🐱 Chore

#90 [Feature] 메인페이지 스터디 게시글 가져오는 로직 추가
  src/assets/defaultImage.jpeg
  src/pages/Home.tsx
Labels: 📝 Design, ✨ Feature

#93 [Fix] 글쓰기 페이지 수정
  src/components/SelectBox.tsx
  src/components/Toast.tsx
  src/hooks/useCategory.ts
  src/hooks/useWrite.ts
  src/pages/WritePage.tsx
  src/stores/writeStore.ts
Labels: ☠ Fix

#94 [Fix] postDetail path에 postId 반영
  src/pages/Home.tsx
  src/pages/PreviewPage.tsx
  src/routes/router.tsx
Labels: ☠ Fix

#97 [fix] 배너 경고 로그 해결
  src/components/Banner.tsx
Labels: ☠ Fix

#100 [Feat] 댓글 기능 적용
  .yarn/install-state.gz
  src/components/Modal.tsx
  src/components/comment/CommentForm.tsx
  src/components/comment/CommentList.tsx
  src/pages/AddQuestion.tsx
  src/stores/modalStore.ts
Labels: ✨ Feature

#101 [Design] 로딩 컴포넌트 구현 (#40)
  package.json
  src/assets/loading-animation.json
  src/components/Loading.tsx
  src/pages/Home.tsx
  yarn.lock
Labels: 📝 Design

#103 [fix] 스터디 탭 Title 경로 에러 해결
  src/pages/Home.tsx
Labels: ☠ Fix

#104 [Feat] 게시글 수정 기능 구현
  src/components/RenderMarkdown.tsx
  src/pages/PostDetail.tsx
  src/pages/PreviewPage.tsx
  src/pages/WritePage.tsx
Labels: ✨ Feature
